service: fitbit-telegram-api
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}
    TELEGRAM_API_TOKEN: ${env:TELEGRAM_API_TOKEN}
  region: eu-west-1
  stage: test
  profile: fitbit
  memorySize: 128
  timeout: 10

  exclude:
    - .idea/**
    - fitbit-telegram-node.iml
    - test/**
    - coverage/**
    - config/**
    - ressources/**
    - credentials

functions:
  getUser:
    handler: handler.UserProfileHandler
    events:
      - http:
          path: user
          method: get
  getFoodlog:
    handler: handler.FoodLogHandler
    events:
      - http:
          path: foodlog/{date}
          method: get
          request:
            parameters:
              paths:
                date: true
  addToFoodlog:
    handler: handler.AddToFoodlogHandler
    events:
      - http:
          path: foodlog
          method: post
  receiveTelegramMessage:
    handler: handler.TelegramMessageHandler
    events:
      - http:
          path: im/telegram
          method: post
