service: fitbit-telegram-api
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    TELEGRAM_API_TOKEN: ${file(./config.yml):telegramToken}
    TELEGRAM_CHAT_ID: ${file(./config.yml):telegramChatId}
    SECURITY_TOKEN: ${file(./config.yml):securityToken}
    CLIENT_ID: ${file(./config.yml):fitbitClientId}
    DYNAMODB_TABLE: ${file(./config.yml):dynamoDBTableName}
  region: eu-west-1
  stage: test
  #profile: fitbit
  memorySize: 128
  timeout: 10
  iamRoleStatements:
  -  Effect: Allow
     Action:
       - dynamodb:*
     Resource: ${file(./config.yml):dynamoDBARN}

  exclude:
    - .idea/**
    - fitbit-telegram-node.iml
    - test/**
    - coverage/**
    - config/**
    - ressources/**
    - credentials

functions:
  receiveTelegramMessage:
    handler: handler.TelegramMessageHandler
    events:
      - http:
          path: im/telegram/{token}
          method: post
          request:
            parameters:
               paths:
                 token: true
  reminderBudgetBeforeMeal:
    handler: handler.TelegramMealReminder
    events:
      - schedule: cron(55 6 * * ? *)
      - schedule: cron(55 10 * * ? *)
      - schedule: cron(55 17 * * ? *)
  receiveOAuthAccessToken:
      handler: handler.FitbitOAuthResponseHandler
      events:
        - http:
            path: auth/fitbit
            method: get
            cors: true
