service: fitbit-telegram-api
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}
    TELEGRAM_API_TOKEN: ${env:TELEGRAM_API_TOKEN}
    CHAT_ID: ${env:CHAT_ID}
  region: eu-west-1
  stage: test
  profile: fitbit
  memorySize: 128
  timeout: 10

  exclude:
    - .idea/**
    - fitbit-telegram-node.iml
    - test/**
    - coverage/**
    - config/**
    - ressources/**
    - credentials

functions:
  receiveTelegramMessage:
    handler: handler.TelegramMessageHandler
    events:
      - http:
          path: im/telegram
          method: post
  reminderBudgetBeforeMeal:
    handler: handler.TelegramMealReminder
    events:
      - schedule: cron(55 6 * * ? *)
      - schedule: cron(55 10 * * ? *)
      - schedule: cron(55 17 * * ? *)
