service: fitbit-telegram-api
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    TELEGRAM_API_TOKEN: ${env:TELEGRAM_API_TOKEN}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}
    SECURITY_TOKEN: ${env:SECURITY_TOKEN}
    CLIENT_ID: ${env:CLIENT_ID}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    DYNAMODB_ARN: ${env:DYNAMODB_ARN}
  region: eu-west-1
  stage: test
  #profile: fitbit
  memorySize: 128
  timeout: 10
  iamRoleStatements:
  -  Effect: Allow
     Action:
       - dynamodb:*
     Resource: ${env:DYNAMODB_ARN}

  exclude:
    - .idea/**
    - fitbit-telegram-node.iml
    - test/**
    - coverage/**
    - config/**
    - ressources/**
    - credentials

functions:
  receiveTelegramMessage:
    handler: handler.TelegramMessageHandler
    events:
      - http:
          path: im/telegram/{token}
          method: post
          request:
            parameters:
               paths:
                 token: true
  reminderBudgetBeforeMeal:
    handler: handler.TelegramMealReminder
    events:
      - schedule: cron(55 6 * * ? *)
      - schedule: cron(55 10 * * ? *)
      - schedule: cron(55 17 * * ? *)
  receiveOAuthAccessToken:
      handler: handler.FitbitOAuthResponseHandler
      events:
        - http:
            path: auth/fitbit
            method: get
            cors: true
